FROM node:18-alpine

ARG WORK_DIR=/usr/src/app
ARG PORT=3000

RUN apk add --no-cache ffmpeg

WORKDIR $WORK_DIR

# copy package files
COPY package.json yarn.lock ./

# install modules
RUN yarn install --frozen-lockfile

EXPOSE $PORT 9229

ENTRYPOINT ["yarn"]

CMD ["start:dev"]
