version: '3.8'

services:
  postgres:
    #env_file:
      #- .env
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      #test: ["CMD-SHELL", "pg_isready -d assetize -U assetize"]
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6378:6378"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 10

  mailhog:
    image: mailhog/mailhog:latest
    #restart: always
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - "1025:1025"
      - "8025:8025"

  matomo-db:
    image: mariadb
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - matomo-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    env_file:
      - .env

  app:
    image: matomo:fpm-alpine
    restart: always
    links:
      - matomo-db
    volumes:
      # - ./config:/var/www/html/config:rw
      # - ./logs:/var/www/html/logs
      - matomo-app:/var/www/html
    environment:
      - MATOMO_DATABASE_HOST=matomo-db
      - PHP_MEMORY_LIMIT=2048M
  #    env_file:
  #      - .env

  web:
    image: nginx:alpine
    restart: always
    volumes:
      - matomo-app:/var/www/html:ro
      # see https://github.com/matomo-org/matomo-nginx
      - ./matomo.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - ${MATOMO_APP_PORT}:80
    env_file:
      - .env

  #api:
    #container_name: api
    #build:
      #context: .
      #target: development
    #volumes:
      #- .:/usr/src/app
      #- /usr/src/app/node_modules
    #ports:
      #- "127.0.0.1:3000:3000"
    #command: "npm run start:dev"
    #depends_on:
      #postgres:
        #condition: service_healthy
      #redis:
        #condition: service_healthy
    #env_file:
      #- .env
volumes:
  pg-data:
  matomo-db:
  matomo-app: