FROM node:18-alpine As development

WORKDIR /usr/src/app

COPY ./package.json ./
COPY ./yarn.lock ./
RUN yarn install --frozen-lockfile --only=development

COPY . .

RUN npm run build

FROM node:18-alpine as production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

# copy package files
COPY ./package.json ./
COPY ./yarn.lock ./

# install modules
RUN yarn install --frozen-lockfile --only=production

COPY . .

COPY --from=development /usr/src/app/dist ./dist

CMD ["node", "dist/main"]